### ISSUE TITLE
Critical: Extract not removing some rules

### ISSUE THREAD

**Issue by bakaat** [pocketjoso/penthouse#102]
Hi,

We've got a problem where some css rules are not properly extracted from the source file. In rule

    .spinner {
      position:relative;
      width:1em;
      height:1em;
      font-size:32px;
      border-bottom:2px solid;
      overflow:hidden;
      text-indent:100%;
      -webkit-animation:.5s spinner linear infinite;
      animation:.5s spinner linear infinite}

The same rule inlined

    .spinner {
      position: relative;
      width: 1em;
      height: 1em;
      font-size: 32px;
      border-bottom-width: 2px;
      border-bottom-style: solid;
      border-bottom-color: initial;
      overflow-x: hidden;
      overflow-y: hidden;
      text-indent: 100%;
      -webkit-animation-name: spinner;
      -webkit-animation-duration: 0.5s;
      -webkit-animation-timing-function: linear;
      -webkit-animation-delay: initial;
      -webkit-animation-iteration-count: infinite;
      -webkit-animation-direction: initial;
      -webkit-animation-fill-mode: initial;
    }

we're using critical 0.6 and inline-critical 0.4.0 but we have the same issue after upgrading to critical 0.7 and inline-critical 1.0

any help or suggestions please ?

**Comment by pocketjoso** [comment]
Hi,
Sorry for the late reply, I thought I had already responded!

I haven't documented this properly - what happens is that the AST parser in Penthouse fails to parse your full css due to errors, so in order to understand your css it is passed a browser instance, from which valid css is extracted. This valid css however has all shorthand syntax expanded, causing the extra declarations you see.

The way to "solve" this for you is to make sure your css is valid (then it will be used as is). You can find the errors in your css that the AST bails on in this AST Explorer:
http://iamdustan.com/reworkcss_ast_explorer/

**Comment by pocketjoso** [comment]
I'm going to close this because I opened more specific issues instead. Feel free to continue to comment!

**Comment by bakaat** [comment]
Good stuff thanks. Will need to take a look at out css so.

**Comment by bakaat** [comment]
Actually, I've just tested our 2 stylesheets using the link you've provided. Neither has shown any errors :/

**Comment by pocketjoso** [comment]
Hard for me to debug without any specifics. Is it possible for you to share the url you're generating critical css for?

If you're running Penthouse directly you can pass the `strict: true` flag and it will throw when the AST parser crashes, rather than trying to normalise the css via a browser instance.

**Comment by henrynho** [comment]
because I get the following error, which realize good thing , Greetings
"There was a problem generating our critical path CSS. Check your URL, or try again later."

**Comment by henrynho** [comment]
this ir URL"http://henrynho.github.io/history-ships/"

**Comment by pocketjoso** [comment]
@henrynho - I just tested and there is no problem generating critical css for that url. The problem in your case must be with the css you're pasting, that it's invalid. Try validating it first, f.e. via this link:
 http://iamdustan.com/reworkcss_ast_explorer/

**Comment by henrynho** [comment]
thanks for your help , excuse my ignorance but how it works   http://iamdustan.com/reworkcss_ast_explorer/  to validate , Greetings

**Comment by henrynho** [comment]
thanks for your help , excuse my ignorance but how it works in order to validate it , I have pasted the css where there tells me but that follows , Greetings
