### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by alexeymakarov90** [pocketjoso/penthouse#114]
It would be great if there was an option to set a cookie/localStorage params for session-kind / oauth authentication for pages. For example, adding critical css to "cart" view fails because you have to be authenticated to see it :).

**Comment by pocketjoso** [comment]
Hi,
Do you need auth handling for generating critical css for dedicated authed-only pages? Or is it a url which has different content depending on whether you have a logged in user or not? I'm just asking because in the latter case you would have to generate and serve different criticalcss depending on user login.

In either case, I'm happy to accept PRs. I don't really have time to add code to this project right now, but this should change in the future.

**Comment by pocketjoso** [comment]
No response here, let's go through the more generic #135 issue instead.
