### ISSUE TITLE
Using custom HTTP header

### ISSUE THREAD

**Issue by ysm001** [pocketjoso/penthouse#135]
I'd like to send custom HTTP header in the case that application's UI changes depends on HTTP header. For example, in the case that the contents changes depends on login state (Authentication header).
(It might be possible to achieve it by modifying [customHeaders](http://phantomjs.org/api/webpage/property/custom-headers.html) of phantomJS.)

**Comment by pocketjoso** [comment]
Hi, sorry for such a late reply.
Do you think the [username/password basic HTTP authentication](http://phantomjs.org/api/webpage/property/settings.html) is enough for your use case?

I don't have time to look at this right now unfortunately, but should be quite easy to add. Feel free to create a PR if you have time, otherwise I'll get around to it eventually.

**Comment by pocketjoso** [comment]
Custom page headers have been supported for a while, check out the readme.
Closing for now, just comment if there are more things that need to be worked out and we can re-open.
