### ISSUE TITLE
Debug Phantom.js?  (Too many styles being removed)

### ISSUE THREAD

**Issue by buob** [pocketjoso/penthouse#136]
First, I was ecstatic that this tool existed.  So glad people are working on this kind of thing, so thanks for all your hard work on this!

I just tried to start using this (with gulp) with the following:

```javascript
gulp.task('penthouse', function() {
  penthouse({
    url: 'http://localhost:8888/website_refresh/build',
    css: './build/css/screen.css',
    height: 1920,
    width: 1080
  }, function(err, criticalCss) {
    console.log(criticalCss);
  });
});
```

It's only giving me pretty much enough for the fixed header, some button styles, and about 10% of the hero (in fact if I change the width and height to 10x10 it's not much different).  I'm assuming this is a problem with the snapshot that phantom is taking of the screen, is there an easy way to debug what phantom is seeing?

Thanks again for all of the work on this!  Seems like an incredible tool!

**Comment by pocketjoso** [comment]
Hi,
Thanks for the positive feedback!

Debugging what goes wrong in these cases is unfortunately a bit of a hassle. The issue is almost guaranteed to be something in your css not being parser correctly. You can start by everything that the AST looks correct for your css here:
http://iamdustan.com/reworkcss_ast_explorer/

**Comment by pocketjoso** [comment]
*mobile typos*
Parsed*
..start by *checking* that the...

**Comment by buob** [comment]
Sorry about the delay -- yeah I had actually [posted my css in there](http://iamdustan.com/reworkcss_ast_explorer/#/cUOIRiV6V4) and it didn't necessarily shout at me, not sure if I'm just looking in the wrong place.

**Comment by pocketjoso** [comment]
Okay, the css looks OK to me too (although some tiny errors can be hard to spot).

Regarding what Penthouse sees (via PhantomJS) - it renders your full page (not just a snapshot), but it does so with JS blocked (as JS is not part of the first render). Does your page have all the content you expect critical styles for in the HTML?

Also, if it's possible for you to share a public url for your page I can have a quick look myself.

**Comment by buob** [comment]
Javascript isn't modifying the content of the page, if that's what you mean.  Typekit is doing some hiding/showing based on body classes and whether the font has been loaded, but other than that, it should look right without javascript.

Here's the page: https://www.teamgantt.com/build/index.html

**Comment by pocketjoso** [comment]
Hi,
started looking at this tonight, what I can see so far:
* The critical css is incorrect for your url - lots of styles are missing. Don't use it until we've figured out what's going wrong and how to fix it.  
* Something seems to go wrong parsing your base64 encoded `background-image: url()` declarations for `logo-top`, haven't figured out what yet as the declaration seems valid - seems related to minification though.
* Something else is wrong too since styles are still being lost even with those rules temporarily disabled.

Will have more time to debug during the weekend.

**Comment by pocketjoso** [comment]
Hi again @buob, sorry for the delay.

All issues are related to minification, which for your css causes issues with the AST parser Penthouse is using. I'm looking for alternatives, but until then I tested and it should work fine for you can just use original (non minified) css as input. Can you confirm this?

**Comment by pocketjoso** [comment]
@boub, any update? Will close issue for now - but will re-open if my comment doesn't resolve your issue. Just let me know.
