### ISSUE TITLE
CSS extracted has no media queries and it takes priority over the external css file that includes media queries

### ISSUE THREAD

**Issue by josenobile** [pocketjoso/penthouse#145]
I have this HTML structure

    `body > footer > div.container > div > <div class="col l3 s12">

`The extracted CSS for such element is
.row .col.s12 {
    width: 100%;
    margin-left: auto;
    left: auto;
    right: auto;
}

But the CSS for such element is in the external css file:

@media only screen and (min-width: 993px)
.row .col.l3 {
    width: 25%;
    margin-left: auto;
    left: auto;
    right: auto;
}

But the inline css takes precedence over the css with media queries in the external css file.

![image](https://cloud.githubusercontent.com/assets/1683657/20243399/ca162392-a923-11e6-8251-2e296f72f35d.png)

I'm testing in my 1920 px viewport screen, and in the settings I set width: 1920, // viewport width

My Suggestion is include any media and not media query because we don't know in advanced which device will receive the content, In my case I need calculate a priority css per each page for ALL devices/resolutions.

Is possible fix it by changing some settings or Can you fix it?

**Comment by pocketjoso** [comment]
Hmm, so your media query rule (993px) is not kept in the critical css. Can you paste your css in [here](http://iamdustan.com/reworkcss_ast_explorer/) to check if it finds any errors in your stylesheet? If not, is it possible to share your url and I can do some tests? If there are really rules that are missing in the critical css, it is almost always due to invalid css throwing off the css parser.

> But the inline css takes precedence over the css with media queries in the external css file.

They shouldn't, this means you have them in the wrong order on the page. You original styles should appear after the critical css in your html.

**Comment by josenobile** [comment]
The CSS has no errors, I have the strict option enabled. I have to set a viewport of 4000px width and now the rule was included. Also I change the order of the JS (the way to insert it too, following the last Google Developers suggestion) and it works.
![image](https://cloud.githubusercontent.com/assets/1683657/20251732/99039214-a9e9-11e6-8b8b-2af89a9ffa3c.png)

**Comment by pocketjoso** [comment]
So all good now?

**Comment by josenobile** [comment]
Yes. Thank you.

An offtopic question, please:
Can I use penthouse by passing the HTML code instead of make an HTTP request? I'm considering to move to Critical for this.

**Comment by pocketjoso** [comment]
If you mean passing HTML instead of CSS, then you should use critical, which does exactly this.
