### ISSUE TITLE
Strict mode by default?

### ISSUE THREAD

**Issue by glebm** [pocketjoso/penthouse#165]
Seems like CSS parsing errors are ignored by default. I did not expect that.
Perhaps it would make sense to enable strict mode by default?

**Comment by pocketjoso** [comment]
Well, Penthouse tries to deal with them the same as all the modern browsers do, and just be forgiving and move on. It is useful in order to help people get through and actually improve the performance of their sites, and not get stuck and improving CSS validation - a task for a different day.

Hence I believe strict mode `false` is the better default. What are your thoughts?
