### ISSUE TITLE
puppeteer@1.0 upgrade

### ISSUE THREAD

**Issue by hummal** [pocketjoso/penthouse#226]
Test & update puppeteer to the released 1.0 version

**Comment by pocketjoso** [comment]
Thanks. Would love to upgrade but is blocked by:
https://github.com/GoogleChrome/puppeteer/issues/1506

which in turn is blocked by:
https://bugs.chromium.org/p/chromium/issues/detail?id=781133#c4

**Comment by simllll** [comment]
Any news on this? 1.1 is out, is it still a blocker? I'm on aws Linux, have no chance to install several actually unsupported versions of puppeteer. I have 1.1 running, will test as soon as I have time. Thought maybe someone has news on this already?

**Comment by simllll** [comment]
My results so far with "my special AWS setup":
I have installed: Google Chrome 64.0.3282.167 

I run penthouse with a custom puppeteer instance and a config like this:
```
penthouse({
                                        url: `file:///${tmpPath}`,
                                        cssString,
                                        forceInclude: [
                                            /^\.sb-/,
                                        ],
                                        puppeteer: {
                                            getBrowser: () => puppeteer.launch({
            executablePath: '/opt/google/chrome/google-chrome',
            args: ['--disable-gpu']
        }),
                                        }
```
I include the url via "file:///", the css via string.

Results: This works perfectly fine in my scenario. 
(Besides one API change in 1.x, page.setRequestInterceptionEnabled(true) changed to await page.setRequestInterception(true)

Therefore I have created a PR (#231) for this API change, otherwise people can't use a newer version with "getBrowser"-fct.

Thanks
Simon

**Comment by pocketjoso** [comment]
> I include the url via "file:///", the css via string.
> Results: This works perfectly fine in my scenario.

Well, but was the page really rendered and correct critical css returned? AFAIK the blocking issue is still there (https://github.com/GoogleChrome/puppeteer/issues/1506).

Since this seem to take ages for the Chrome team to fix (cc @addyosmani if there's anything you can do to speed this up) -what I'm considering doing is updating to the latest puppeteer in a new Penthouse version, and just clearly document that Penthouse (and critical) users must stay on the current version if they want to be able to use the file protocol with local files... it's not ideal but I too want to be able to use the latest puppeteer version.

**Comment by simllll** [comment]
I have seen the open issue, but in my scenario (with latest chrome stable version) a correct critical css is returned! I have tested several situations and different pages. Generated critical css is identical to the one penthouse has generated with phantomjs. 

Maybe it has something to do with chrome vs. Chromium. Or the issue has even been fixed? Can you test with a non-custom build of latest chromium/puppeteer 1.1?

Simon

**Comment by simllll** [comment]
Alright, this is indeed related to chrome vs. chromium.

If I take your test script from https://github.com/GoogleChrome/puppeteer/issues/1506 and set the executablePath to chrome (Which is btw Google Chrome 64.0.3282.140) the output is correct.

```js
const puppeteer = require('puppeteer');
(async() => {
const browser = await puppeteer.launch({
 executablePath: '/usr/bin/google-chrome-stable',
      // waitUntil: 'networkidle2', // see if this performs better than default for timeouts
      ignoreHTTPSErrors: true,
      args: ['--disable-setuid-sandbox', '--no-sandbox']
    })
...
```

test with chrome:
```
[Function: url]
content: <html><head></head><body>
		<h1>test</h1>
	


</body></html>

```

test with chromium (no exectuable set):
```
[Function: url]
content: <html><head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">&lt;html&gt;
	&lt;body&gt;
		&lt;h1&gt;test&lt;/h1&gt;
	&lt;/body&gt;
&lt;/html&gt;

</pre></body></html>

```

Well, at least we know the bug is still there.. but not present in latest chrome stable ;)

Regards
Simon

**Comment by simllll** [comment]
Something else that came into my mind:
Content-Security-Policy.

The interception is only needed to block external JS, well.. we use a state of the art browser, that actually supports Content-Security-Policy.

I've just tested it, if I insert 
`    <meta http-equiv="Content-Security-Policy" content="script-src 'self'">`
in my generated html file, all external JS is not loaded.

I don't know puppeteer so well, but maybe there is an option to set the content security policy manually? Or disable the interception for file:/// includes and make a big note that people need to insert a Content Policy like the one I mentioned if they wanna go with this approach?

Just some thoughts. let me know ;)

Simon
ps.: for me the latter approach would be perfectly suited, I already insert a <base href=""> tag in my content before I pass it to penthouse.

**Comment by simllll** [comment]
And one more comment .. this problem is really interesting ;)

Basically the reason why I have a "file:///" is that I actually have the document content already. So what I do now is writing the file to disc and opening it again in puppeteer. But even better would be that I can keep this direclty in memory.

By allowing a new parmeter (e.g. content) for puppeteer. (Url will be ingored if content is set...)
And if content is set we intercept the first file. We can even add a check if url is a file, load the file with fs.readFile and then use the content of it to inject via this approach.

```
await page.setRequestInterception(true)
page.once('request', (request) => {
request.respond({body: document});
page.on('request', requestFwd => requestFwd.continue());
});
await page.goto('http://localhost');
```
Tested it and works perfectly with puppeteer 1.1.

Let me know what you think about it, I can create a PR.

Simon

**Comment by pocketjoso** [comment]
@simllll I admire your enthusiasm. :) Ideally I don't want to have any hacks in Penthouse for this; there is no reason long term to bypass the `file://` protocol which is meant for exactly this purpose. As you say it does work in Chrome, but it was broken in Chromium a little while back - [here is the Chromium bug tracking this](https://bugs.chromium.org/p/chromium/issues/detail?id=781133#c4).

Let me think about your hack in the mean time, maybe there is no better option until this gets fixed in Chromium.

**Comment by simllll** [comment]
Well, I understand but I'm not quite sure if I would consider it as hack. It even gives us a new feature for penthouse - it allows to pass html document content directly to penthouse/puppeteer. Which would be great for my (and I guess for a lot of other people who are using "file:///") use cases.

See https://github.com/simllll/penthouse/commit/e9ab3a0d7bcef6c46f0eae1bc777cd32b7949648 for a quick implementation. The biggest change is actually in the blockJSRequests flag. The rest is quite short. Tested it with latest puppeteers. Check it out ;) npm test should work (at least it does like with the orignail source - on my environment test 1 fails without any real reason (content looks identical)).

For the new feature: you can pass "<html>
<head>
    <meta http-equiv="Content-Security-Policy" content="script-src 'self'">
    <script src="https://assets-cdn.github.com/assets/frameworks-6a1a4c5fba77.js" type="application/javascript"></script>
</head>
	<body>
		<h1>test</h1>
	</body>
</html>" as string to "url"!

Regards

**Comment by hummal** [comment]
this is done as I can see

**Comment by pocketjoso** [comment]
Yep!
