### ISSUE TITLE
Issue with forceInclude options

### ISSUE THREAD

**Issue by pradeepb6** [pocketjoso/penthouse#264]
I have repeated class names in css files. 

For example: I am using [Remodal](https://github.com/vodkabears/Remodal) plugin. It adds wrapper for the modal by the class name `remodal-wrapper`. I am adding additional styling to the `remodal-wrapper` class in custom css file. And I am also including the css file provided by the plugin(it has some styling for `remodal-wrapper`). 

Now, for `forceInclude` option, If I add `[/^\.remodal-wrapper(.*)/]`, Its not generating critical css for that class.  

If I add any other class names which are unique, it works just fine. 

Is it supposed to be like that or am I missing something here?

PS:
To overcome the above issue, I was thinking of using `cssString`. But after using it, critical css generated by `css` option is no more available.

**Comment by pradeepb6** [comment]
First of all thank you for your time. 

I want to add modal css to critical because, by the time my css files are loaded in the browser, the contents inside the modal are visible and it looks ugly for user experience. So I want to hide the contents by adding `display: none` to critical css. 

And I am pretty sure, they were part of my css. I experimented by adding unique classes(to `less` file and to `forceinclude`) and it worked. But if I add `remodal-wrapper` in place unique class, it didn't. So I thought , it does not work if there are repeated class names in case files. 

Please correct me if I am wrong.

**Comment by pocketjoso** [comment]
Okay, thanks for the explanation. Shouldn't you be able set display none
for the whole modal in the critical css, and then reset it in the full css
- only after the JS has loaded? It's what I would do in this case.

For the force include. To debug, would you consider adding a test for this
in penthouse, via a PR? Otherwise I'll get around to it eventually. To see
and fix any potential bug here.

Le jeu. 12 juil. 2018 08:40, Pradeep Baradur <notifications@github.com> a
écrit :

**Comment by pradeepb6** [comment]
Sure. I need to check how can I add the test.  I will be adding it in some days. Until then I will close the ticket.
