### ISSUE TITLE
Can penthouse be used with webpack?

### ISSUE THREAD

**Issue by Genuifx** [pocketjoso/penthouse#270]
It seems penthouse is friendly with SPA, Can penthouse be used with webpack? if yes, Is there any example or documentation?

**Comment by pocketjoso** [comment]
Regarding SPA, same answer as in critical repo:
> if your SPA is server side rendered, i.e. html contains the same content as your SPA presents, then yes, it will work fine.

> If you require Javascript to show content, then there's no point. Your first render, if you try to use critical css, will be blank (as JS has not loaded yet).

Penthouse can be used together with webpack. Exactly how depends on how you use webpack, particularly whether you let webpack generate your html or not. When I use penthouse together with webpack, I trigger the critical css generation after the webpack (production) build finishes. At this point I have the updated stylesheet(s) that I can feed into penthouse. I take care of generating the html myself so I can insert the critical css as expected.

If you want a fully automated approach, I believe some people have made plugins for webpack, but I don't have any up to date list of such plugins at the moment. If you go looking, it would be great if you reported back, since it could be a good idea listing this info in this repo (or in critical).
