### ISSUE TITLE
CLI version?

### ISSUE THREAD

**Issue by Macleykun** [pocketjoso/penthouse#313]
I just used your critical css program, and it seems to work really well, and i was wondering to automate this with github workflow!

I'm sadly not really a programmer, and more used to the CLI. I think it would be nice to have the ability to add critical css on the fly for production :)

**Comment by pocketjoso** [comment]
Hi - thanks for the feedback!

In an automated flow I think the complexity would be about the same whether you were using a CLI or not. Did you see the examples in this repo? They should work for your automated flow, for example the [queue example to generate critical css for many urls](https://github.com/pocketjoso/penthouse/blob/master/examples/many-urls.js). Instead of calling a penthouse CLI, you would call your JS file (like the many-urls example file I linked to above).

**Comment by Macleykun** [comment]
I've seen a couple of examples, however i'm not familiar with javascript at all, hence the idea of a cli haha
I read trough the example, and i see where i can throw the url's in, however i'm not sure where the css should be referd to be put into the html files.

So that we get smth like:
domain.com > get css > put in index.html
domain.com/page1 > get css > put in page1.html
etc etc

If i understand how to do that, i can make it a workflow, test it and then contribute it back for others to use!

**Comment by pocketjoso** [comment]
Have you seen the critical tool?
https://github.com/addyosmani/critical/

It is built on top of penthouse, and automatically handles both extracting the CSS from a page, as well as inlining the critical css afterwards. They also offer a CLI.

It sounds like this is exactly what you are looking for.

**Comment by Macleykun** [comment]
ah yes, i think i used it before, i think i should try again and see if i can get it to work!
Thanks for your advice and time!

**Comment by Macleykun** [comment]
So, i tried for a couple of days to use their program but, for some reason it never output any inline critical css. It always put the whole html or css file withoud any modifications.

I understand if this is out of scope of this issue/project, but you have any clue how to use their cli or some sort of way to add critical css to each html from all css? Putting that command/script in github workflow will be easy, just the core way is what i'm stuck at.

**Comment by pocketjoso** [comment]
I think you will get better responses directly from their repo.

If the returned html didn't include any inlined critical css then there must have been something missing in the way you called their program. I suggest you re-open your issue in that repo, and include exactly the code (command) you tried using, that didn't work for you.

**Comment by Macleykun** [comment]
True, i'm just afraid the repo is abdoned and that i never get a reply from them
Nevertheless, i'll try again and i hope they'll respond

thanks for your help and your work! gonna close this forreals now haha

**Comment by pocketjoso** [comment]
It's not abandoned; you can see more active development there (if you look at pull requests etc) than in this repo even.

You will need to add more information about the command you are trying to run though; otherwise it will be a pain for anyone to try to help you, by guessing what you have done and not... so at least just copy paste your CLI command into that issue so others can follow. Good luck!
