### ISSUE TITLE
Force include

### ISSUE THREAD

**Issue by bitinn** [pocketjoso/penthouse#61]
Not a big deal, but nice to have:

Imagine you have a header at the top of page that shows currently login user (otherwise display a login button), because such info is only visible to login users, `penthouse` won't be able to see that this class is used (it will only inline the login button's css).

While one can argue most existing users should have a cached copy of full css in their browser anyway, there are indeed cases where a login user can run into problems (though eventually the full css will load and all should be fine at that point).

This does make `penthouse` look a bit like [criticalCSS](https://github.com/filamentgroup/criticalCSS), which has this feature but lack self-signed ssl support for local development. But I guess these 2 tools serves very similar purpose so it's natural to see their feature set converges :)

**Comment by pocketjoso** [comment]
Hi, thanks for opening this issue. While critical css is most important for new users, I do agree that it's also useful for logged in users, as they can remain logged while their cached css has become redundant due to new release.

I'm not sure I'm in favour of `forceInclude`. It moves the critical css task away from being automated, which is what I really strive for it to be. It also ties you to your current css and html/js, meaning you have to keep updating it all the time. The manual work going in to figuring out what selectors need to be forced can also already today be used into just concatenating the `critical css` given by `Penthouse` with the extra css you've figured out you need for `logged in` users.

I'm thinking an ability to set a `cookie` with login info would be more useful; you can then produce a logged in and a logged out critical css for each page. Would that solve your use case?

And yeah of course `Penthouse` looks similar to `criticalCSS`; these two tools basically do the same thing.

**Comment by bitinn** [comment]
> I'm thinking an ability to set a cookie with login info would be more useful

I agree, something like a `--cookie` flag should work and keep the burden away from developers. But I have no experience with phantomjs so can't tell if it's possible.

**Comment by pocketjoso** [comment]
You can set cookies with `phantomjs`, but that approach won't work for session cookies... I'll have a think about it.

**Comment by pocketjoso** [comment]
Setting a `session cookie` with phantomJS in `Penthouse` requires too much custom logic to be worthwhile.

@bitinn Would it be possible for you to generate html for logged in pages in your build process, and pass these files to `Penthouse`? That would bypass the need for `Penthouse` to deal with any auth logic - it would just generate `critical css` for the `html` provided.

**Comment by bitinn** [comment]
> Would it be possible for you to generate html for logged in pages in your build process, and pass these files to Penthouse?

Yeah that would be an option, some might even end up generating inline css for multiple pages. For larger project perhaps this is a better option than force include (because difficult to keep track of CSS, but easier to generate a view).

**Comment by pocketjoso** [comment]
> Yeah that would be an option, some might even end up generating inline css for multiple pages. For larger project perhaps this is a better option than force include (because difficult to keep track of CSS, but easier to generate a view).

Yeah that's exactly why we do it - you can automate it this way in a way you can't using `forceInclude`.

Given this, would you still use `forceInclude` if I implemented it?

**Comment by bitinn** [comment]
> Given this, would you still use forceInclude if I implemented it?

I am a bit torn on this: on one hand I only need to include 2 more class names, so `forceInclude` is definitely the easier choice, on the other hand generated views would be the longterm choice but our current system doesn't allow that flexibility yet (when it comes to login user view).

Maybe you can shred some light on how do you guys generated a page specifically for `penthouse`?

**Comment by pocketjoso** [comment]
> Maybe you can shred some light on how do you guys generated a page specifically for penthouse? Do you use mock user data or something?

We serve a page just in the same way as we would for a web request, but we chose values for dynamic properties (logged in user, which topic to display on a (dynamic) topic page, etc). If we would have mocked this data we would have had to manually keep it up to date when our api changes, so instead we just pick resource id's, and pull down real data from our actual api.

So it works roughly like this: Pick dynamic properties, f.e. user (id) `14123124123` -> pull the full data for picked resources (f.e. `user`) -> render `html` with the picked properties and pulled data -> use html with `penthouse`

**Comment by pocketjoso** [comment]
Resolved by #64.
