### ISSUE TITLE
Drop standalone support and move into Node

### ISSUE THREAD

**Issue by pocketjoso** [pocketjoso/penthouse#68]
#### Background
The standalone CLI support has been supported from the start with the intention to make it easier for non developers to use Penthouse, by not requiring them to first setup `Node`. A year in now it seems to me that very few people use this option, and if that if anything at all it is command line they want to avoid, which they achieve by using the [hosted online version of Penthouse](http://jonassebastianohlsson.com/criticalpathcssgenerator/). The standalone option therefor seems redundant.

Standalone support has also required @fatso83 to write a lot of custom code (f.e. options parser) because we couldn't rely on node modules. It also means we have two maintain two versions of the code, and all the code to automate creating those versions etc.

#### Future
Let's discuss in this thread.

**Comment by pocketjoso** [comment]
So many things will come out of this change, but the first will be to modify the internal api's between `penthouse` components, and between the node module and the penthouse core/wrapper - so let's focus on this first.

@fatso83 Following on from our previous discussions, what do you think about using something like [node-phantom](https://github.com/alexscheelmeyer/node-phantom)?

**Comment by fatso83** [comment]
Laying sick in a French country cottage gives some room for chatting, but
unfortunately not development :-)

The node bridge using socket.io seems like a great fit. Using some code
from the Phantomjs cluster library we can probably also handle multiple
calls quite efficiently. So quite optimistic on this one. We might actually
see a small performance drop due to the communication overhead, but with
all these timeouts being used that is the least of anyone's problems :-)
Background

The standalone CLI support has been supported from the start with the
intention to make it easier for non developers to use Penthouse, by not
requiring them to first setup Node. A year in now it seems to me that very
few people use this optiod, and if they want to avoid anything it is
command line tools altogether, by using the hosted online version of
Penthouse <http://jonassebastianohlsson.com/criticalpathcssgenerator/>. It
therefor seems redundant.

Standalone support has also required @fatso83 <https://github.com/fatso83>
to write a lot of custom code (f.e. options parser) because we couldn't
rely on node modules. It also means we have two maintain two versions of
the code, and all the code to automate creating those versions etc.
Future

Let's discuss in this thread.

—
Reply to this email directly or view it on GitHub
<https://github.com/pocketjoso/penthouse/issues/68>.

**Comment by pocketjoso** [comment]
> We might actually
see a small performance drop due to the communication overhead

Hopefully what we lose in overhead for a single call we can gain back for multiple calls. I also presume we're talking about less than seconds here?

> but with all these timeouts being used that is the least of anyone's problems

What timeouts exactly are you referring to?

Rest and get better!

**Comment by fatso83** [comment]
I would believe that the biggest part would be played by the establishment
of the bidirectional socket. But less than a second, unless something weird
is happening.

I was just referring to the timeouts employed when the pages are loading
asynchronous external resources, etc. Don't remember if we handle this or
not? Or when penthouse has too much work to be done in the default amount
of time.
8. aug. 2015 20.38 skrev "Jonas Ohlsson" <notifications@github.com>:

**Comment by fatso83** [comment]
I was about to start tinkering now, but looking a bit closer at node-phantom, I see it has been stale for a few years. Not a good sign with an issues list that long ... So I think betting on [PhantomJS-Node](https://github.com/sgentle/phantomjs-node) would be a safer choice.

On the other, after looking at the code for PhantomJS-Node and Phantom Cluster (which builds upon the first), I totally see why node-phantom was created, as there are so many layers in there: rpc layers, http, websockets, ... I have used the afternoon looking at the source and hopefully we will never need to know about any of that. I looked into some issues in Phantom Cluster about instances not being killed, but I don't think that applies to us as we have pretty short lived processes. I guess we'll figure out.

I think I'll just start out with the easy stuff first: using phantomjs-node, and so this cluster thing can wait until later as it has pretty much the same interface.

**Comment by pocketjoso** [comment]
Yeah I read the ['no really how does it work'](https://github.com/sgentle/phantomjs-node#no-really-how-does-it-work) section on `phantomjs-node` and.. that's pretty insane.

As long as it's stable, actively maintained, and does what we won't that shouldn't have to bother us though. Would be good to get any kind of proof of concept up as soon as possible so we can validate that the approach works before going to deep. :)

**Comment by pocketjoso** [comment]
Standalone support now dropped in [0.4.0](https://github.com/pocketjoso/penthouse/releases/tag/v.0.4.0), so closing this.

Work to replacing the current bridge between Node and phantom is still outstanding, and so [replacing the custom options parser](https://github.com/pocketjoso/penthouse/issues/80)

**Comment by josenobile** [comment]
Anyone who want use it as a command is easy as:

var penthouse = require('penthouse'),
    path = require('path'),
    fs = require('fs'),
    __basedir = './';
//penthouse.DEBUG = true;
penthouse({
    url: process.argv[2],
    css: process.argv[3],


And you do something like

node csspriority.js https://www.hostingfacil.co/ /home/hostingfacil/public_html/css/cssZ5tmbH.css

The first parameter is the URL and the second is the CSS File.
