### ISSUE TITLE
Possibility to provide a glob pattern for the css option

### ISSUE THREAD

**Issue by thasmo** [pocketjoso/penthouse#77]
Would be cool to provide a glob pattern for the css option:
```js
css: 'public/styles/*.css'
```

**Comment by pocketjoso** [comment]
Hi, thanks for opening up an issue.
My initial thoughts are that this globbing can easily be done outside of `Penthouse`, and is therefor better done left outside it? Also, it what use case would you want to create critical css from a different subset of css than what you're serving in production? (i.e. don't you already have concatenated css file(s)?)

**Comment by thasmo** [comment]
Hey! Yeah, I've concatenated all CSS into a single file already, but I thought about having an easier way to read the CSS file with penthouse without knowing it's exact filename and without the need to use a dedicated configuration option for it, where I would set the path to the file.

The reason is that my gulp.js task reads all `*.scss` files from within my source directory, compiles it to CSS and saves it to the public directory. In my case I only have a `main.scss` file there, which then gets compiled to `main.css` and I'd like penthouse to use this file but without explicitely defining it's name.

That's why using a glob would make sense because if I rename the file, it would still work without changing the penthouse configuration. Although I know this can bring up problems, because maybe someone doesn't want to read  *all* CSS files from within the public directory, but then it's still possible to define the exact path to a single file.

I guess you're right with the fact that using the glob function outside penthouse makes more sense. How would this look like? I guess it would not be possible like this, because penthouse possibly won't handle an array of file paths:
```js
penthouse({
    url: 'http://google.com',
    css: glob.sync('public/*.css'),
    width: 1300,
    height: 900
}, function(err, criticalCss) {
    // ...
});
```

Thanks for your feedback on this!

**Comment by CameronGregory** [comment]
G'Day Jonas,
     How's it going?  I had recently turned off cpcss, because it was 
behaving weirdly.  Anyway, today I finally figured out what I think is 
going on.

home page: without cpcss

<html .. head...
load css

...
<style>
inline css "AA"
..
</style>

content...

<footer>

===============
home page: with cpcss

<html .. head...
<style>
inline cpcss
</style>
...
<style>
inline css "AA"
..
</style>

content...

footer (load css)

=====

So I think what is happening is that with the cpcss, the ordering is 
changing... since now the full css is loaded at the end, it overwrites 
the inline ones (the ones in "AA")

thoughts?

only solution I can quickly think of is to have no inline overwriting css.

Cameron

**Comment by pocketjoso** [comment]
G'day Cameron,
Everythings good with me, how are you?

What are those AA styles for? If they're meant to override the regular
styles in the full css file, then yes, the ordering will get messed up if
the footer load css inserts the full css at the end of the page (because
the full css will then override the AA css). These problems would go away
if you instead loaded your full css in the `head` tag - but async.

There is no `asyn` tag for css `link`s, so we have to do it with
javascript. Because we do it with javascript, we provide a `noscript`
fallback. In the head of your document, insert a script tag with content
like this:

```

<script>
 // loadCSS slightly adapted from: https://github.com/filamentgroup/loadCSS
  function loadCSS(n,e,o,d){"use strict";var
t=window.document.createElement("link"),i=e||window.document.getElementsByTagName("script")[0],l=window.document.styleSheets;return
t.rel="stylesheet",t.href=n,t.media="only
x",d&&(t.onload=d),i.parentNode.insertBefore(t,i),t.onloadcssdefined=function(e){for(var
o,d=0;d<l.length;d++)l[d].href&&l[d].href.indexOf(n)>-1&&(o=!0);o?e():setTimeout(function(){t.onloadcssdefined(e)})},t.onloadcssdefined(function(){t.media=o||"all"}),t}
 loadCSS(<FULL CSS HREF>); // f.e.
'/styles/jso.min/css'</script><noscript><link rel='stylesheet'
href=<FULL CSS HREF> /></noscript>
```

This should sort out your problem and as a bonus load your full css
slightly faster (then before when you used cpcss).

Cheers,
Jonas



On Sat, Oct 17, 2015 at 10:32 AM, Cameron Gregory <notifications@github.com>
wrote:

> G'Day Jonas,
> How's it going? I had recently turned off cpcss, because it was
> behaving weirdly. Anyway, today I finally figured out what I think is
> going on.
>
> home page: without cpcss
>
> <html .. head...
> load css
>
> ...
> <style>
> inline css "AA"
> ..
> </style>
>
> content...
>
> <footer>
>
> ===============
> home page: with cpcss
>
> <html .. head...
> <style>
> inline cpcss
> </style>
> ...
> <style>
> inline css "AA"
> ..
> </style>
>
> content...
>
> footer (load css)
>
> =====
>
> So I think what is happening is that with the cpcss, the ordering is
> changing... since now the full css is loaded at the end, it overwrites
> the inline ones (the ones in "AA")
>
> thoughts?
>
> only solution I can quickly think of is to have no inline overwriting css.
>
> Cameron
>
>
> On 10/17/2015 07:10 PM, Jonas Ohlsson wrote:
> >
> > Hi, thanks for opening up an issue.
> > My initial thoughts are that this globbing can easily be done outside
> > of |Penthouse|, and is therefor better done left outside it? Also, it
> > what use case would you want to create critical css from a different
> > subset of css than what you're serving in production? (i.e. don't you
> > already have concatenated css file(s)?)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/pocketjoso/penthouse/issues/77#issuecomment-148896936>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pocketjoso/penthouse/issues/77#issuecomment-148898813>
> .
>



-- 
https://jonassebastianohlsson.com <http://jonassebastianohlsson.com>
@pocketjoso <http://twitter.com/pocketjoso>

**Comment by pocketjoso** [comment]
@thasmo Sorry for late reply, I thought I already responded but must have forgotten.

I would suggest putting your css file name for your concatenated css in some config so you don't have to do extra work to process your (s)css files twice (not just concatenate but also minification etc). Should be simple in your case, and if you were to add dynamic generation of the css file name (f.e. via unique hash) you could just write the generated file name to file. Then here were you call `Penthouse` you just read the css file name from this ~ config.

.. if you really don't want to go down this route you would have to repeat what you do in your css build here - glob, then concatenate, then save to file.. then pass that file to Penthouse. I wouldn't recommend it though. :)

Closing this as I don't think it is necessary for Penthouse to support globbing - feel free to continue commenting regardless!
